apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "crowdsec-firewall-bouncer.fullname" . }}
  labels:
    {{- include "crowdsec-firewall-bouncer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "crowdsec-firewall-bouncer.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: {{ .Values.daemonset.updateStrategy }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | quote }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "crowdsec-firewall-bouncer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "crowdsec-firewall-bouncer.fullname" . }}
      automountServiceAccountToken: false
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: {{ .Values.daemonset.terminationGracePeriodSeconds }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
        {{- with omit .Values.nodeSelector "kubernetes.io/os" }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . | quote }}
      {{- end }}
      containers:
        - name: bouncer
          image: "{{ .Values.image.repository }}@{{ .Values.image.digest }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/crowdsec-firewall-bouncer
          args:
            - -c
            - /config/crowdsec-firewall-bouncer.yaml
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret.name }}
                  key: {{ .Values.existingSecret.key }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          startupProbe:
            tcpSocket:
              port: metrics
            {{- toYaml .Values.probes.startup | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: metrics
            {{- toYaml .Values.probes.readiness | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: metrics
            {{- toYaml .Values.probes.liveness | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: run
              mountPath: /run
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: config
          configMap:
            name: {{ include "crowdsec-firewall-bouncer.fullname" . }}-config
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
