apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crowdsec-firewall-bouncer.fullname" . }}
  labels:
    {{- include "crowdsec-firewall-bouncer.labels" . | nindent 4 }}
automountServiceAccountToken: false
