{{- if and .Values.metrics.enabled .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "crowdsec-firewall-bouncer.fullname" . }}-metrics
  labels:
    {{- include "crowdsec-firewall-bouncer.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "crowdsec-firewall-bouncer.selectorLabels" . | nindent 4 }}
{{- end }}
